// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- MERGED METADATA OBJECT ---
export const metadata: Metadata = {
  title: "VibeTogether",
  description: "Generated by create next app",
  icons: {
    // This generates <link rel="icon" ...> with rel="icon"
    icon: '/favicon.ico', 

    // This generates <link rel="apple-touch-icon" ...> with rel="apple-touch-icon"
    apple: '/apple-icon.png', 
  },
};
// ------------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
